
package co.com.claro.webservice.odi;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "requestPortType", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RequestPortType {


    /**
     * 
     * @param part1
     * @return
     *     returns co.com.claro.webservice.odi.OdiStartType
     */
    @WebMethod(action = "xmlns.oracle.com/odi/OdiInvoke/invokeStartScen")
    @WebResult(name = "OdiStartScenResponse", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
    @Action(input = "xmlns.oracle.com/odi/OdiInvoke/invokeStartScen", output = "xmlns.oracle.com/odi/OdiInvoke/requestPortType/invokeStartScenResponse")
    public OdiStartType invokeStartScen(
        @WebParam(name = "OdiStartScenRequest", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
        OdiStartScenRequest part1);

    /**
     * 
     * @param part1
     */
    @WebMethod(action = "xmlns.oracle.com/odi/OdiInvoke/invokeStartScenWithCallback")
    @Oneway
    @Action(input = "xmlns.oracle.com/odi/OdiInvoke/invokeStartScenWithCallback")
    public void invokeStartScenWithCallback(
        @WebParam(name = "OdiStartScenWithCallbackRequest", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
        OdiStartScenWithCallbackRequest part1);

    /**
     * 
     * @param part1
     * @return
     *     returns co.com.claro.webservice.odi.OdiGetSessionsStatusResponse
     */
    @WebMethod(action = "xmlns.oracle.com/odi/OdiInvoke/getSessionStatus")
    @WebResult(name = "OdiGetSessionsStatusResponse", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
    @Action(input = "xmlns.oracle.com/odi/OdiInvoke/getSessionStatus", output = "xmlns.oracle.com/odi/OdiInvoke/requestPortType/getSessionStatusResponse")
    public OdiGetSessionsStatusResponse getSessionStatus(
        @WebParam(name = "OdiGetSessionsStatusRequest", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
        OdiGetSessionsStatusRequest part1);

    /**
     * 
     * @param part1
     * @return
     *     returns co.com.claro.webservice.odi.GetWebServiceVersionResponse
     */
    @WebMethod(action = "xmlns.oracle.com/odi/OdiInvoke/getVersion")
    @WebResult(name = "getWebServiceVersionResponse", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
    @Action(input = "xmlns.oracle.com/odi/OdiInvoke/getVersion", output = "xmlns.oracle.com/odi/OdiInvoke/requestPortType/getVersionResponse")
    public GetWebServiceVersionResponse getVersion(
        @WebParam(name = "getWebServiceVersionRequest", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
        GetWebServiceVersionRequest part1);

    /**
     * 
     * @param part1
     * @return
     *     returns co.com.claro.webservice.odi.OdiStartType
     */
    @WebMethod(action = "xmlns.oracle.com/odi/OdiInvoke/invokeRestartSess")
    @WebResult(name = "OdiRestartSessResponse", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
    @Action(input = "xmlns.oracle.com/odi/OdiInvoke/invokeRestartSess", output = "xmlns.oracle.com/odi/OdiInvoke/requestPortType/invokeRestartSessResponse")
    public OdiStartType invokeRestartSess(
        @WebParam(name = "OdiRestartSessRequest", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
        OdiRestartSessRequest part1);

    /**
     * 
     * @param part1
     */
    @WebMethod(action = "xmlns.oracle.com/odi/OdiInvoke/invokeRestartSessWithCallback")
    @Oneway
    @Action(input = "xmlns.oracle.com/odi/OdiInvoke/invokeRestartSessWithCallback")
    public void invokeRestartSessWithCallback(
        @WebParam(name = "OdiRestartSessWithCallbackRequest", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
        OdiRestartSessWithCallbackRequest part1);

    /**
     * 
     * @param part1
     * @return
     *     returns co.com.claro.webservice.odi.OdiStartLoadPlanResponse
     */
    @WebMethod(action = "xmlns.oracle.com/odi/OdiInvoke/invokeStartLoadPlan")
    @WebResult(name = "OdiStartLoadPlanResponse", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
    @Action(input = "xmlns.oracle.com/odi/OdiInvoke/invokeStartLoadPlan", output = "xmlns.oracle.com/odi/OdiInvoke/requestPortType/invokeStartLoadPlanResponse")
    public OdiStartLoadPlanResponse invokeStartLoadPlan(
        @WebParam(name = "OdiStartLoadPlanRequest", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
        OdiStartLoadPlanRequest part1);

    /**
     * 
     * @param part1
     * @return
     *     returns co.com.claro.webservice.odi.OdiStopLoadPlanResponse
     */
    @WebMethod(action = "xmlns.oracle.com/odi/OdiInvoke/invokeStopLoadPlan")
    @WebResult(name = "OdiStopLoadPlanResponse", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
    @Action(input = "xmlns.oracle.com/odi/OdiInvoke/invokeStopLoadPlan", output = "xmlns.oracle.com/odi/OdiInvoke/requestPortType/invokeStopLoadPlanResponse")
    public OdiStopLoadPlanResponse invokeStopLoadPlan(
        @WebParam(name = "OdiStopLoadPlanRequest", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
        OdiStopLoadPlanRequest part1);

    /**
     * 
     * @param part1
     * @return
     *     returns co.com.claro.webservice.odi.OdiRestartLoadPlanResponse
     */
    @WebMethod(action = "xmlns.oracle.com/odi/OdiInvoke/invokeRestartLoadPlan")
    @WebResult(name = "OdiRestartLoadPlanResponse", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
    @Action(input = "xmlns.oracle.com/odi/OdiInvoke/invokeRestartLoadPlan", output = "xmlns.oracle.com/odi/OdiInvoke/requestPortType/invokeRestartLoadPlanResponse")
    public OdiRestartLoadPlanResponse invokeRestartLoadPlan(
        @WebParam(name = "OdiRestartLoadPlanRequest", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
        OdiRestartLoadPlanRequest part1);

    /**
     * 
     * @param part1
     * @return
     *     returns co.com.claro.webservice.odi.OdiGetLoadPlanStatusResponse
     */
    @WebMethod(action = "xmlns.oracle.com/odi/OdiInvoke/getLoadPlanStatus")
    @WebResult(name = "OdiGetLoadPlanStatusResponse", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
    @Action(input = "xmlns.oracle.com/odi/OdiInvoke/getLoadPlanStatus", output = "xmlns.oracle.com/odi/OdiInvoke/requestPortType/getLoadPlanStatusResponse")
    public OdiGetLoadPlanStatusResponse getLoadPlanStatus(
        @WebParam(name = "OdiGetLoadPlanStatusRequest", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
        OdiGetLoadPlanStatusRequest part1);

    /**
     * 
     * @param part1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "xmlns.oracle.com/odi/OdiInvoke/refreshAgentConfig")
    @WebResult(name = "OdiRefreshAgentConfigResponse", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
    @Action(input = "xmlns.oracle.com/odi/OdiInvoke/refreshAgentConfig", output = "xmlns.oracle.com/odi/OdiInvoke/requestPortType/refreshAgentConfigResponse")
    public String refreshAgentConfig(
        @WebParam(name = "OdiRefreshAgentConfigRequest", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
        OdiRefreshAgentConfigRequest part1);

}
