
package com.oracle.xmlns.odi.odiinvoke;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OdiInvoke", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", wsdlLocation = "http://172.24.42.164:8100/oraclediagent/OdiInvoke?wsdl")
public class OdiInvoke
    extends Service
{

    private final static URL ODIINVOKE_WSDL_LOCATION;
    private final static WebServiceException ODIINVOKE_EXCEPTION;
    private final static QName ODIINVOKE_QNAME = new QName("xmlns.oracle.com/odi/OdiInvoke/", "OdiInvoke");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.24.42.164:8100/oraclediagent/OdiInvoke?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ODIINVOKE_WSDL_LOCATION = url;
        ODIINVOKE_EXCEPTION = e;
    }

    public OdiInvoke() {
        super(__getWsdlLocation(), ODIINVOKE_QNAME);
    }

    public OdiInvoke(WebServiceFeature... features) {
        super(__getWsdlLocation(), ODIINVOKE_QNAME, features);
    }

    public OdiInvoke(URL wsdlLocation) {
        super(wsdlLocation, ODIINVOKE_QNAME);
    }

    public OdiInvoke(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ODIINVOKE_QNAME, features);
    }

    public OdiInvoke(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OdiInvoke(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RequestPortType
     */
    @WebEndpoint(name = "OdiInvokeRequestSOAP11port0")
    public RequestPortType getOdiInvokeRequestSOAP11Port0() {
        return super.getPort(new QName("xmlns.oracle.com/odi/OdiInvoke/", "OdiInvokeRequestSOAP11port0"), RequestPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RequestPortType
     */
    @WebEndpoint(name = "OdiInvokeRequestSOAP11port0")
    public RequestPortType getOdiInvokeRequestSOAP11Port0(WebServiceFeature... features) {
        return super.getPort(new QName("xmlns.oracle.com/odi/OdiInvoke/", "OdiInvokeRequestSOAP11port0"), RequestPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ODIINVOKE_EXCEPTION!= null) {
            throw ODIINVOKE_EXCEPTION;
        }
        return ODIINVOKE_WSDL_LOCATION;
    }

}
