
package co.com.claro.service.soap.odi.consumer;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "requestPortTypeCallback", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RequestPortTypeCallback {


    /**
     * 
     * @param part1
     */
    @WebMethod(action = "xmlns.oracle.com/odi/OdiInvoke/invokeRestartSessCallback")
    @Oneway
    @Action(input = "xmlns.oracle.com/odi/OdiInvoke/invokeRestartSessCallback")
    public void invokeRestartSessCallback(
        @WebParam(name = "OdiRestartSessResponse", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
        OdiStartType part1);

    /**
     * 
     * @param part1
     */
    @WebMethod(action = "xmlns.oracle.com/odi/OdiInvoke/invokeStartScenCallback")
    @Oneway
    @Action(input = "xmlns.oracle.com/odi/OdiInvoke/invokeStartScenCallback")
    public void invokeStartScenCallback(
        @WebParam(name = "OdiStartScenResponse", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
        OdiStartType part1);

}
